# Generated by Django 3.0.5 on 2020-05-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
